[package]
name = "mellow"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
lazy_static = "1.5.0"
prometheus = "0.14.0"
redis = "0.25"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
